### ISSUE TITLE
GUI MVP

### ISSUE THREAD

**Issue by sowbug** [ensnare-org/ensnare#13]
These are some ideas for getting the GUI MVP done.

Patterns

- [x] All patterns are the same size. Pattern size is determined by global time signature. For example, 4/4 is 4 beats long, and each beat is 4 divisions. 3/4 is 3 beats long, and each beat is 4 divisions.
- [x] Patterns can be arranged only on measure boundaries, again determined by global time signature.
- [x] Pattern notes are 1/16 of a measure in duration.
- [x] The pattern editor always shows min/max notes plus a little extra (so we don't have to do zooming/panning right away).

Arrangements

- [x] The note arrangements are only patterns.
- [x] Drag from carousel to arrangement to arrange a pattern.
- [x] Select and press Delete to remove.
- [x] ~~Drag an arranged pattern to move it.~~ (DEFERRED for #18)
- [x] ~~Option-drag to copy.~~ (DEFERRED for #18)
- [x] Select, then control-D to replicate arranged pattern.
- [x] Don't worry about drag visuals for now.
- [x] Arrangement always shows min/max plus a few more measures (same reason as for pattern editor).
- [ ] If the current track has a drumkit instrument in it, then the pattern editor renders for drums instead (I think we can do better than this).

Misc

- [x] Use the side panel for selected instrument detail.
- [x] ~~Use the bottom panel for composer view.~~ (DEFERRED for #36)
- [x] Come back to [egui_tiles](https://github.com/rerun-io/egui_tiles) and see if they're easy to use.
